### ISSUE TITLE
ERROR when run get method 

### ISSUE THREAD

**Issue by websashka** [Trinketer22/func_docker#4]
INFO: 🚀 You want to interact with your contracts ['contract'] in testnet - that's great!
INFO: 🦘 Found existing deploy-wallet [kQC2jMc2YJjtf2V1Maq3YP7lRLckEi5dROb7RWwxhmMhnHfd] (Balance: 1.019619007💎, Is inited: True) in /root/.config/toncli
INFO: 👯 [contract] [kQA9gET3CHF1zIbQmFbTrh0WqsMW5nc6oEI59PiETTThK5EK] runmethod ['get_total']
ERROR: 👻 There is a problem when trying to run get method of contract
ERROR: using liteserver 1 with addr [65.108.204.54:29296]
zerostate set to -1:823F81F306FF02694F935CF5021548E3CE2B86B529812AF6A12148879E95A128:67E20AC184B9E039A62667ACC3F9C00F90F359A76738233379EFA47604980CE8
latest masterchain block known to server is (-1,8000000000000000,5238296):DB7C52D932E748535F95ED4D62D72DBF75F97A12B992EA60F8B7D66A39DAB2CA:52CA634BC2D3129DDDE716C1D2260B7CB7FADAEF94B218404C3CE9899FB493D7 created at 1670172552 (16 seconds ago)
BLK#1 = (-1,8000000000000000,5238296):DB7C52D932E748535F95ED4D62D72DBF75F97A12B992EA60F8B7D66A39DAB2CA:52CA634BC2D3129DDDE716C1D2260B7CB7FADAEF94B218404C3CE9899FB493D7
BLK#2 = (-1,8000000000000000,0):823F81F306FF02694F935CF5021548E3CE2B86B529812AF6A12148879E95A128:67E20AC184B9E039A62667ACC3F9C00F90F359A76738233379EFA47604980CE8

**Comment by Trinketer22** [comment]
Hi! Congrats on being first issue creator!
It doesn't seem  like contract is being initialized(deployed) though:https://testnet.tonscan.org/address/EQA9gET3CHF1zIbQmFbTrh0WqsMW5nc6oEI59PiETTThKyqA#transactions
That's why you can't get it's data.
